# Generated by Django 5.1.6 on 2025-04-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowanalytics",
            name="execution_time",
            field=models.FloatField(default=0),
        ),
    ]
