# Generated by Django 5.1.6 on 2025-04-20 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0004_workflowexecution_execution_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="execution_time",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
