# Generated by Django 5.1.6 on 2025-04-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0005_workflowexecution_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowexecution",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
