# Generated by Django 5.1.6 on 2025-04-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcomparison',
            name='compared_models',
            field=models.ManyToManyField(related_name='comparisons', to='ai_integration.aimodelconfig'),
        ),
    ]
