# Generated by Django 5.1.6 on 2025-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0002_modelcomparison_compared_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
    ]
