# Generated by Django 5.1.6 on 2025-04-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_integration", "0002_nodeport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("provider", models.CharField(max_length=100)),
                ("model_type", models.CharField(max_length=100)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
